spring:
  application:
    name: strivesync-api
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/strivesync
    username: strivesync
    password: strivesync
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
    open-in-view: false
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
  
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:5tR1v3SyNc_S3cR3t_K3y_F0r_JWT_T0k3n_G3n3r4t10n}
      expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

# Logging Configuration
logging:
  level:
    root: INFO
    com.strivesync: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Custom Application Properties
app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization
    allow-credentials: true
    max-age: 3600

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    displayRequestDuration: true
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.strivesync.api.controller
  paths-to-match: /** 