spring:
  application:
    name: strivesync-api
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/strivesync
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  
  # Flyway Migration Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  
  # Security Configuration
  security:
    filter:
      order: 10

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:veryLongAndSecureSecretKeyThatShouldBeStoredInEnvironmentVariables}
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

# Logging Configuration
logging:
  level:
    root: INFO
    com.strivesync: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  packages-to-scan: com.strivesync.api.controller 